version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backend # 인스턴스에서 파일이 저장될 위치
    overwrite: yes
permissions:
  - object: /home/ubuntu/backend
    #    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: chabak-deploy.sh    # locaiton 기준 => project root 디렉토리
      timeout: 60
      runas: root
